# Generated by Django 3.2.5 on 2021-07-15 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasesIncrementCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_inc', models.IntegerField(default=0)),
                ('date_before', models.TextField(default=0)),
                ('present_date', models.TextField(default=0)),
                ('death_inc', models.IntegerField(default=0)),
                ('recovered_inc', models.IntegerField(default=0)),
                ('Dated', models.TextField(default='2021-07-15')),
            ],
        ),
        migrations.CreateModel(
            name='district_cases',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(default='city', max_length=100)),
                ('state_name', models.CharField(default='state', max_length=50)),
                ('confirmed', models.IntegerField(blank=True, default=0)),
                ('Death', models.IntegerField(blank=True, default=0)),
                ('Recovered', models.IntegerField(blank=True, default=0)),
                ('Active', models.IntegerField(blank=True, default=0)),
                ('Dated', models.TextField(default='2021-07-15')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='states_cases',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(default='state', max_length=50, unique=True)),
                ('confirmed', models.IntegerField(blank=True, default=0)),
                ('Death', models.IntegerField(blank=True, default=0)),
                ('Recovered', models.IntegerField(blank=True, default=0)),
                ('Active', models.IntegerField(blank=True, default=0)),
                ('Dated', models.TextField(default='2021-07-15')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
