# Generated by Django 3.1.2 on 2021-02-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district_cases',
            name='city_name',
            field=models.CharField(default='city', max_length=100),
        ),
    ]
