# Generated by Django 3.2.5 on 2021-07-15 08:54

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('modified', models.DateTimeField()),
            ],
        ),
    ]
