# Generated by Django 3.1.2 on 2021-02-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidtracker', '0003_auto_20210209_2146'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasesIncrementCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed_inc', models.IntegerField(default=0)),
                ('date_before', models.TextField(default=0)),
                ('present_date', models.TextField(default=0)),
                ('death_inc', models.IntegerField(default=0)),
                ('recovered_inc', models.IntegerField(default=0)),
                ('Dated', models.TextField(default='2021-02-10')),
            ],
        ),
        migrations.DeleteModel(
            name='cases_inc',
        ),
        migrations.AlterField(
            model_name='district_cases',
            name='Dated',
            field=models.TextField(default='2021-02-10'),
        ),
        migrations.AlterField(
            model_name='states_cases',
            name='Dated',
            field=models.TextField(default='2021-02-10'),
        ),
    ]
