# Generated by Django 3.1.2 on 2021-02-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='district_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(default='city', max_length=50)),
                ('state_name', models.CharField(default='state', max_length=50)),
                ('confirmed', models.IntegerField(blank=True, default=0)),
                ('Death', models.IntegerField(blank=True, default=0)),
                ('Recovered', models.IntegerField(blank=True, default=0)),
                ('Active', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='states_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(default='state', max_length=50, unique=True)),
                ('confirmed', models.IntegerField(blank=True, default=0)),
                ('Death', models.IntegerField(blank=True, default=0)),
                ('Recovered', models.IntegerField(blank=True, default=0)),
                ('Active', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
